[package]
name = "serial_enumerator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"

[dependencies.windows]
version = "0.29.0"

[[bin]]
name = "lser"
path = "src/bin/lser.rs"